# Generated by Django 5.1.1 on 2025-03-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
