# Generated by Django 5.1.1 on 2025-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_creds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('therapist', 'Therapist')], max_length=10)),
            ],
        ),
    ]
