# Generated by Django 5.1.1 on 2025-03-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_creds',
            new_name='UserCreds',
        ),
    ]
