# Generated by Django 5.0.6 on 2025-03-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_gad7response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gad7response',
            old_name='date_taken',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='gad7response',
            name='user',
        ),
    ]
